
#To sit it properly, visit the mod wiki website for more information:
#https://github.com/ixDarkLorD/ModpackManager/wiki
[Manifest]
	#Modpack Title | Syntax: ${version}, ${mcversion}, ${gamestate}
	title = "Survival Remastered ${version} - ${gamestate}"
	#Modpack Version
	version = "v1.1.2"
	#Modpack Identifier
	identifier = "survival-remastered"
	project_id_or_url = "523374"

[Visuals]
	#Durability Display Visibility and Size
	durability_display_visibility = false
	#Range: 0.0 ~ 1.0
	durability_display_size = 0.5

[General]
	#Startup Title Visibility and Text
	startup_title_visibility = true
	startup_title_text = "Please wait! Starting up..."
	#Gamestate Visibility Mode | Syntax: ALL, PLAYING_MODE_AND_EXTRA, PLAYING_MODE_AND_PAUSE_SCREEN, ONLY_PLAYING_MODE
	gamestate_visibility = "ALL"
	#Startup Loading Visibility and Text
	loading_screen_gamestate_visibility = true
	loading_screen_text = "Loading the game..."
	#CFU Button(Checking for Updates) Behavior
	is_first_time_pressed = true

