areDyeCauldronsEnabled = true
doDyeCauldronsObeyPrecipitation = false
arePotionCauldronsEnabled = true
doPotionCauldronsObeyPrecipitation = false
areCakesStackable = true
arePufferfishBuffed = true
isSharpnessBuffed = true
areShulkersDyeable = true
areShulkersDyeableInSurvival = false
doesMagicBypassProtection = false
isSugarcaneBonemealable = true
areAnvilsPushable = true
jukeboxEmitRedstoneWhenPlaying = true
chargedCreeperHeadLimit = -1
