areDyeCauldronsEnabled = true
doDyeCauldronsObeyPrecipitation = true
arePotionCauldronsEnabled = true
doPotionCauldronsObeyPrecipitation = true
areCakesStackable = true
arePufferfishBuffed = true
isSharpnessBuffed = false
areShulkersDyeable = true
areShulkersDyeableInSurvival = false
doesMagicBypassProtection = false
isSugarcaneBonemealable = true
areAnvilsPushable = true
jukeboxEmitRedstoneWhenPlaying = true
chargedCreeperHeadLimit = -1
