mineshaftSpawnRate = 0.003
minY = -55
maxY = 30

[spawnRates]
lanternSpawnRate = 0.0067
torchSpawnRate = 0.03
workstationSpawnRate = 0.025
workstationDungeonSpawnRate = 0.25
smallShaftSpawnRate = 0.07
cobwebSpawnRate = 0.15
smallShaftChestMinecartSpawnRate = 0.00125
mainShaftChestMinecartSpawnRate = 0.01
smallShaftTntMinecartSpawnRate = 0.0024999999441206455
mainShaftTntMinecartSpawnRate = 0.0024999999441206455
zombieVillagerRoomSpawnChance = 3
smallShaftPieceChainLength = 9

[ores]
enabled = true
cobble = 55
coal = 25
iron = 10
redstone = 8
gold = 8
lapis = 4
emerald = 4
diamond = 3
