#Whether immersives on anvils and smithing tables should be allowed
anvil_immersion = true
#Whether immersives on brewing stands should be allowed
brewing_immersion = true
#Whether immersives on all types of chests should be allowed. Unless users enable right_click_chest, this is VR only.
chest_immersion = false
#Whether immersives on crafting tables should be allowed
crafting_immersion = true
#Whether immersives on furnaces should be allowed
furnace_immersion = true
#Whether immersives on jukeboxes should be allowed (VR only)
jukebox_immersion = true
#Allow VR users to grab items at a distance.
ranged_grab = true
#Whether VR users can physically push buttons
button_immersion = true
#Whether immersives on Enchanting Tables should be allowed
enchant_table_immersion = true
#Whether VR users can hold items above a campfire to cook them
campfire_immersion = true
#Whether VR users can physically toggle levers
lever_immersion = true
#Allow VR players to use a bag to manage their inventory
bag_inventory = true
#Whether VR users can adjust the delay of repeaters using their hands
repeater_immersion = true
#Whether VR users can open/close doors and fence gates using their hands
door_immersion = true
#Whether VR users can swing a hoe to till ground and harvest wheat
hoe_immersion = true
#Whether VR users can pet animals they've tamed (or animals that are tamed for all once tamed, like horses)
can_pet = true
#Whether VR users can equip armor by placing the armor on them
armor_immersion = true
#Whether VR users can feed animals using both hands
feed_animals = true
#Whether immersives on Shulker Boxes should be allowed
shulker_box_immersion = true
#Whether VR players can pet any living entity instead of just pets that they're owners of. Requires 'can_pet' to be enabled!
can_pet_any_living = false
#Whether VR users can use a more immersive shield. They only need to hold a shield in the direction to block, no need to right click!
immersive_shield = true
#Range in blocks that VR players can pick up items using ranged grab. Set to -1 to use Minecraft's pick range.
#Range: -1 ~ 12
ranged_grab_range = 8
#Whether immersives on beacons should be allowed
beacon_immersion = true
#Whether immersives on barrels should be allowed
barrel_immersion = true
#Allow users to crouch + right-click to bypass immersives.
crouch_bypass_immersion = true
#Color for the bag as a base-10 RGB number.
#Range: 0 ~ 16777215
bag_color = 11901820
#Puts the bag on the other side of your arm. Set to true if you're left-handed.
left_handed_bag = false
#Allows for right-clicking chests to use their immersive. Works outside of VR!
right_click_chest = false
#Makes the furnace immersive more centered instead of similar to the vanilla GUI
center_furnace = false
#Makes the brewing stand more centered instead of similar to the vanilla GUI
center_brewing = false
#Use lower-detailed bag
low_detail_bag = false
#The mode for the placement guide
#Range: 0 ~ 2
placement_guide_mode = 0
#Integer representation for the mode to use when placing items using ImmersiveMC
#Range: 0 ~ 3
placement_mode = 0
#Whether the item output of a crafting table should spin
spin_crafting_output = true
#Allow right-clicking immersives in VR, like how NonVR users do.
right_click_in_vr = false
#Enables compatability for 3D resource packs like Classic 3D (16x)
resource_pack_3d_compat = false

