contributorCosmetic = ""
globalTooltip = true
tooltipWrapWidth = 200
noMicrosoftTelemetry = true

[debug]
tagsTooltip = false
debugTooltipMsg = false
NBTTooltipFormatter = "vanilla"
NBTTooltip = false
