# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = false
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "simple"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				furnace = true
				dropper = true
				daylight_detector = true
				jukebox = true
				sign = true
				brewing_stand = true
				sculk_sensor = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				trapped_chest = true
				blast_furnace = true

			[light_sources.settings.block_entities.seasons]
				greenhouse_glass = true
				season_detector = true

			[light_sources.settings.block_entities.vanillatweaks]
				pedestal = true

			[light_sources.settings.block_entities.buildinggadgets]
				template_manager_tile = true
				effect_block_tile = true

			[light_sources.settings.block_entities.universal_graves]
				grave = true

			[light_sources.settings.block_entities.easymagic]
				enchanting_table = true

			[light_sources.settings.block_entities.goldenhoppers]
				golden_hopper = true

			[light_sources.settings.block_entities.bosses_of_mass_destruction]
				void_lily = true
				mob_ward = true
				void_blossom_block = true
				monolith_block = true
				levitation_block = true

			[light_sources.settings.block_entities.gofish]
				astral_crate = true

			[light_sources.settings.block_entities.graveyard]
				urn_block_entity = true
				gravestone_block_entity = true

			[light_sources.settings.block_entities.blockus]
				wooden_barrel = true

			[light_sources.settings.block_entities.rocks]
				overworld_geyser_blockentity = true
				nether_geyser_blockentity = true

			[light_sources.settings.block_entities.betternether]
				furnace = true
				forge = true
				nether_brewing_stand = true
				chest_of_drawers = true

			[light_sources.settings.block_entities.just_end_anchor]
				end_anchor = true

			[light_sources.settings.block_entities.bountiful]
				board-be = true

			[light_sources.settings.block_entities.oystersreborn]
				oyster_basket = true
				oyster_block_entity = true

			[light_sources.settings.block_entities.adventurez]
				dragon_egg_entity = true
				stone_holder_entity = true
				piglin_flag_entity = true
				shadow_chest_entity = true

			[light_sources.settings.block_entities.agape_space]
				green_lamp = true
				conveyor = true
				airlock_base = true
				motor = true
				catalyzer = true
				powergen = true
				life_support = true
				cloning_device = true
				colony_command = true
				airlock_field = true
				storage = true
				miner_drill = true
				starship_control = true
				fan = true
				electro = true
				portal_beam_block = true
				power_furnace = true
				redstone_motor = true
				gearbox = true
				press = true
				rocket_station = true
				crusher = true
				space_crystal = true
				packer = true
				trigger_block = true
				red_lamp = true
				blue_lamp = true
				sulfur_vent = true
				oxy_gen = true
				fluid_pump = true
				fluid_tank = true
				auto_constructor = true
				wire = true
				luxury_game1 = true
				luxury_game2 = true
				battery_block = true
				starship_powersource = true
				powered_panel = true
				solargen = true

			[light_sources.settings.block_entities.bclib]
				barrel = true
				chest = true
				furnace = true
				sign = true

			[light_sources.settings.block_entities.earthtojavamobs]
				rainbow_bed = true

			[light_sources.settings.block_entities.oxidized]
				copper_kiln_block_entity = true

			[light_sources.settings.block_entities.fractalportals]
				end_fractal = true

			[light_sources.settings.block_entities.infchest]

				[light_sources.settings.block_entities.infchest.tile]
					deque = true
					infchest = true

			[light_sources.settings.block_entities.reinfchest]
				copper_chest = true
				iron_chest = true
				diamond_chest = true
				netherite_chest = true
				gold_chest = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true

			[light_sources.settings.entities.endgoblintraders]
				end_goblin_trader = true

			[light_sources.settings.entities.twm]
				frog = true
				warden = true
				chest_boat = true
				mangrove_boat = true

			[light_sources.settings.entities.elementalcreepers]
				rainbow_creeper = true
				illusion_creeper = true
				miner_tnt = true
				electric_tnt = true
				cookie_tnt = true
				firework_creeper = true
				illusion_tnt = true
				fire_creeper = true
				miner_creeper = true
				water_tnt = true
				fake_illusion_tnt = true
				air_creeper = true
				air_tnt = true
				light_creeper = true
				electric_creeper = true
				fire_tnt = true
				ice_tnt = true
				hydrogen_tnt = true
				dark_creeper = true
				fake_illusion_creeper = true
				firework_tnt = true
				cookie_creeper = true
				magma_creeper = true
				ice_creeper = true
				water_creeper = true
				reverse_tnt = true
				hydrogen_creeper = true
				light_tnt = true
				earth_creeper = true
				earth_tnt = true
				reverse_creeper = true
				magma_tnt = true
				dark_tnt = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

			[light_sources.settings.entities.impaled]
				elder_trident = true
				hellfork = true
				pitchfork = true
				atlan = true
				guardian_trident = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				skeleton_creeper = true
				ghoul = true
				reaper = true

			[light_sources.settings.entities.goblintraders]
				vein_goblin_trader = true
				goblin_trader = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				chair = true
				hydrogen_jellyfish = true
				jungle_skeleton = true
				skull = true
				naga = true

			[light_sources.settings.entities.adventurez]
				skeleton_vanguard = true
				deer = true
				thrown_rock = true
				desert_rhino = true
				small_stone_golem = true
				piglin_beast = true
				blaze_guardian = true
				ender_whale = true
				shaman = true
				dragon = true
				stone_golem = true
				iguana = true
				amethyst_golem = true
				soul_reaper = true
				red_fungus = true
				void_cloud = true
				summoner = true
				void_bullet = true
				orc = true
				the_eye = true
				necromancer = true
				fire_breath = true
				void_fragment = true
				brown_fungus = true
				blaze_guardian_shield = true
				nightmare = true
				mammoth = true
				void_shade = true
				tiny_eye = true
				gilded_stone = true
				wither_puppet = true
				enderwarthog = true
				void_shadow = true
				amethyst_shard = true

			[light_sources.settings.entities.agape_space]
				titan_slime = true
				hoverbike = true
				space_pirate_commander = true
				space_cat = true
				space_mite = true
				laserbeam_arrow = true
				europa_fish = true
				space_pirate = true
				europa_fish_a = true
				rocket_ship = true
				rocket_ship_v3 = true
				rocket_ship_v2 = true

			[light_sources.settings.entities.wilderworld]
				butterfly = true

			[light_sources.settings.entities.boatcontainer]
				ender_chest_boat = true
				chest_boat = true

			[light_sources.settings.entities.gobber2]
				nemesis = true

			[light_sources.settings.entities.vanillatweaks]
				dynamite = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				lich = true
				blue_fireball = true
				spore_ball = true
				obsidilith = true
				petal_blade = true
				comet = true
				gauntlet = true
				soul_star = true
				void_blossom = true

			[light_sources.settings.entities.immersive_portals]
				loading_indicator = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.aqupd]
				grizzly_bear = true

			[light_sources.settings.entities.earthtojavamobs]
				pink_footed_pig = true
				cream_cow = true
				flecked_sheep = true
				midnight_chicken = true
				umbra_cow = true
				rainbow_sheep = true
				mottled_pig = true
				bold_striped_rabbit = true
				long_nosed_sheep = true
				amber_chicken = true
				bouldering_zombie = true
				furnace_golem = true
				vested_rabbit = true
				rotten_flesh_projectile = true
				bronzed_chicken = true
				jumbo_rabbit = true
				bone_shard = true
				moobloom = true
				stormy_chicken = true
				rocky_sheep = true
				fancy_chicken = true
				jolly_llama = true
				moolip = true
				glow_squid = true
				sunset_cow = true
				melon_seed_projectile = true
				pale_pig = true
				piebald_pig = true
				muddy_foot_rabbit = true
				dairy_cow = true
				spotted_pig = true
				skeleton_wolf = true
				gold_crested_chicken = true
				muddy_pig = true
				freckled_rabbit = true
				wooly_cow = true
				ashen_cow = true
				sooty_pig = true
				patched_sheep = true
				melon_golem = true
				harelequin_rabbit = true
				horned_sheep = true
				pinto_cow = true
				cookie_cow = true
				fuzzy_sheep = true
				bone_spider = true
				cluckshroom = true
				albino_cow = true
				viler_witch = true
				inky_sheep = true
				tropical_slime = true
				skewbald_chicken = true
				lobber_zombie = true

			[light_sources.settings.entities.oxidized]
				copper_golem = true

			[light_sources.settings.entities.betterend]
				shadow_walker = true
				cubozoa = true
				end_slime = true
				end_fish = true
				silk_moth = true
				dragonfly = true

			[light_sources.settings.entities.dawn]
				custom_tnt = true
				flying_block = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.squirrels]
				squirrel = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

			[light_sources.settings.entities.dinocraft]
				mosasaurus = true
				sauropod = true
				theropod = true
				stegoraptor = true
				troodon = true

			[light_sources.settings.entities.ottercraft]
				otter = true

			[light_sources.settings.entities.sculk_worm]
				sculk_worm_entity = true
				sculk_segment_entity = true

			[light_sources.settings.entities.betteranimalsplus]
				lamprey = true
				eel_freshwater = true
				horseshoecrab = true
				goose = true
				badger = true
				crab = true
				blackbear = true
				songbird = true
				boar = true
				pheasant = true
				deer = true
				reindeer = true
				coyote = true
				squirrel = true
				feralwolf = true
				turkey = true
				brownbear = true
				lammergeier = true
				moose = true
				walrus = true
				butterfly = true
				nautilus = true
				shark = true
				dragonfly = true
				jellyfish = true
				badgerdirt = true
				eel_saltwater = true
				whale = true
				bobbit_worm = true
				squid_giant = true
				tarantula = true
				piranha = true
				barracuda = true
				flying_fish = true
				octopus = true
				tarantulahair = true
				squid_colossal = true

			[light_sources.settings.entities.extratnt]
				sparkler = true
				fountain = true
				geyser = true
				pink = true
				ultimate = true

			[light_sources.settings.entities.dragonloot]
				dragon_trident = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				dripstone_creeper = true
				spruce_creeper = true
				savannah_creeper = true
				badlands_creeper = true
				jungle_creeper = true
				desert_creeper = true
				swamp_creeper = true
				dark_oak_creeper = true
				beach_creeper = true
				hills_creeper = true
				snowy_creeper = true
				bamboo_creeper = true

			[light_sources.settings.entities.sit]
				entity_sit = true

