
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				sheep = true
				chicken = true
				cow = true
				pig = true
				item = true
				rabbit = true
				chest_minecart = true
				villager = true
				horse = true
				cat = true
				iron_golem = true
				zombie = true
				skeleton = true
				bat = true
				spider = true
				cod = true
				salmon = true
				glow_squid = true
				creeper = true
				enderman = true
				squid = true
				drowned = true
				cave_spider = true
				slime = true
				ender_pearl = true
				witch = true
				arrow = true
				zombie_villager = true
				area_effect_cloud = true
				tropical_fish = true
				axolotl = true
				wolf = true
				fox = true
				item_frame = true
				armor_stand = true
				glow_item_frame = true
				bee = true
				allay = true
				vex = true
				ravager = true
				warden = true
				ocelot = true
				pillager = true
				parrot = true
				evoker = true
				vindicator = true
				experience_orb = true
				pufferfish = true
				dolphin = true
				turtle = true

			[light_sources.settings.entities.wilderwild]
				firefly = true
				jellyfish = true
				crab = true

