enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 48
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 10.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = false
edenring = true
mcwfences = true
farmersdelight = true
mcwroofs = true
nears = true
sihywtcamd = true
alloy_forgery = true
betternether = true
mcwwindows = true
croptopia = true
reinfshulker = true
yttr = true
galosphere = true
betterend = true
friendsandfoes = true
libraryferret = true
gobber2 = true
advanced_reborn = true
mcwpaths = true
mcwlights = true
origins = true
mcwbridges = true
lunade = true
additionaladditions = true
mcwtrpdoors = true
milk = true
earthtojavamobs = true
wilderwild = true
creatures_from_the_snow = true
soundmuffler = true
charm = false
morevillagers = true
graveyard = true
customportalapi = true
creatures_of_the_snow = true
mcwdoors = true
reinfbarrel = true
techreborn = true
mo_glass = true
promenade = true
create = true
seasons = true
geode = true
minecraft = true
mossierdeepslate = true
betterechoshards = true
musica = true
sculk_worm = true
createaddition = true
twilightforest = true
bosses_of_mass_destruction = true
betteranimalsplus = true
immersive_weathering = true
dragonloot = true
infusion_table = true
paradise_lost = true
puddles = true
skylorlib = true
reinfchest = true
blockus = true
