version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.1622777
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = false
azurelib = true
edenring = true
mcwfences = true
farmersdelight = true
nears = true
mcwroofs = true
alloy_forgery = true
sihywtcamd = true
simple_copper_pipes = true
croptopia = true
mcwwindows = true
betternether = true
reinfshulker = true
yttr = true
galosphere = true
betterend = true
friendsandfoes = true
libraryferret = true
gobber2 = true
advanced_reborn = true
mcwpaths = true
mcwlights = true
origins = true
mcwbridges = true
lunade = true
additionaladditions = true
mcwtrpdoors = true
milk = true
earthtojavamobs = true
wilderwild = true
chunkloaders = true
creatures_from_the_snow = true
soundmuffler = true
charm = false
morevillagers = true
graveyard = true
customportalapi = true
creatures_of_the_snow = true
mcwdoors = true
reinfbarrel = true
techreborn = true
mo_glass = true
create = true
endrem = true
promenade = true
seasons = true
geode = true
minecraft = true
mossierdeepslate = true
betterechoshards = true
musica = true
sculk_worm = true
createaddition = true
twilightforest = true
bosses_of_mass_destruction = true
betteranimalsplus = true
immersive_weathering = true
dragonloot = true
bedrockify = true
traverse = true
infusion_table = true
valkyrienskies = true
paradise_lost = true
vs_eureka = true
puddles = true
skylorlib = true
toms_storage = true
cinderscapes = true
reinfchest = true
blockus = true
