removeAnvilXPLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = false
removeAnvilLevelLimit = true
fairLevelCost = true
removeRepairCostIncrease = false
newAnvilLevelLimit = 255
