removeAnvilXPLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = false
removeAnvilLevelLimit = true
fairLevelCost = true
removeRepairCostIncrease = true
newAnvilLevelLimit = 255
