[general]
	clientID = 918296137516085348
	enabled = true
	debugging = false
	configScreen = true
	launcherIntegration = false
	version = 12

[init]
	enabled = true
	description = "Survival Remastered is loading"
	state = "Game Starting..."
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[main_menu]
	enabled = true
	description = "%player% is in the title screen"
	state = "Staring at the title screen"
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[server_list]
	enabled = true
	description = "%player% is finding a server"
	state = "Searching for people"
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[join_game]
	enabled = true
	description = "%player% is joining a game"
	state = "Joining Game"
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[single_player]
	enabled = true
	description = "Currently In %world%"
	state = "Playing without friends"
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[multi_player]
	enabled = true
	description = "Playing on %servername%"
	state = "Has friends?"
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[generic]
	description = "Playing Survival Remastered"
	state = "Survival but its Remastered"
	largeImageKey = "mclogo"
	largeImageText = "Survival Remastered"
	smallImageKey = "mclogo"
	smallImageText = "%mods% mods installed"
	buttons = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"


